# Generated by Django 4.0.1 on 2022-01-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('staff_category', models.CharField(choices=[('FRD', 'FRD'), ('TLR', 'TLR'), ('SEC', 'SEC'), ('OTH', 'OTH')], default='TLR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/pics')),
                ('desc', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_style', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='MALE', max_length=1)),
                ('tailor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_out_time', models.DateTimeField(auto_now_add=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(auto_now_add=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('burst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('round_sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trouser_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('Inches', 'inches'), ('Centimeter', 'cm')], default='inches', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('burst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('under_burst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('half_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('round_sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('breast_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nipple_to_nipple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skirt_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waist_hip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('blouse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('Inches', 'inches'), ('Centimeter', 'cm')], default='inches', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.ManyToManyField(to='apparel.RegisterIn')),
                ('clock_out', models.ManyToManyField(to='apparel.RegisterOut')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=True)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.tailor')),
            ],
        ),
    ]
